// <auto-generated />
using System;
using LectureSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LectureSystem.Migrations
{
    [DbContext(typeof(LectureSystemContext))]
    partial class LectureSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LectureSystem.Entities.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LectureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxEnrollment")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("LectureSystem.Entities.ProgramLecture", b =>
                {
                    b.Property<int>("StudentProgramId")
                        .HasColumnType("int");

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentProgramId", "LectureId");

                    b.HasIndex("LectureId");

                    b.ToTable("ProgramLectures");
                });

            modelBuilder.Entity("LectureSystem.Entities.StudentProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("StudentPrograms");
                });

            modelBuilder.Entity("LectureSystem.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LectureSystem.Entities.Lecturer", b =>
                {
                    b.HasBaseType("LectureSystem.Entities.User");

                    b.HasDiscriminator().HasValue("Lecturer");
                });

            modelBuilder.Entity("LectureSystem.Entities.Student", b =>
                {
                    b.HasBaseType("LectureSystem.Entities.User");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasIndex("SupervisorId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("LectureSystem.Entities.Supervisor", b =>
                {
                    b.HasBaseType("LectureSystem.Entities.User");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("LectureSystem.Entities.Lecture", b =>
                {
                    b.HasOne("LectureSystem.Entities.Lecturer", "Lecturer")
                        .WithMany("Lectures")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("LectureSystem.Entities.ProgramLecture", b =>
                {
                    b.HasOne("LectureSystem.Entities.Lecture", "Lecture")
                        .WithMany("ProgramLectures")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LectureSystem.Entities.StudentProgram", "StudentProgram")
                        .WithMany("ProgramLectures")
                        .HasForeignKey("StudentProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("StudentProgram");
                });

            modelBuilder.Entity("LectureSystem.Entities.StudentProgram", b =>
                {
                    b.HasOne("LectureSystem.Entities.Student", "Student")
                        .WithMany("StudentPrograms")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LectureSystem.Entities.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("LectureSystem.Entities.Student", b =>
                {
                    b.HasOne("LectureSystem.Entities.Supervisor", "Supervisor")
                        .WithMany("Students")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("LectureSystem.Entities.Lecture", b =>
                {
                    b.Navigation("ProgramLectures");
                });

            modelBuilder.Entity("LectureSystem.Entities.StudentProgram", b =>
                {
                    b.Navigation("ProgramLectures");
                });

            modelBuilder.Entity("LectureSystem.Entities.Lecturer", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("LectureSystem.Entities.Student", b =>
                {
                    b.Navigation("StudentPrograms");
                });

            modelBuilder.Entity("LectureSystem.Entities.Supervisor", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
